kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}-route
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Values.app.name }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: {{ .Values.app.name }}-service
    weight: 100
  port:
    targetPort: http-port
  wildcardPolicy: None