apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: cluster
  source:
    path: manifests
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  roles:
    - name: cluster-admins
      policies:
        - 'p, proj:default:cluster-admins, applications, get, default/*, allow'
        - 'p, proj:default:cluster-admins, applications, sync, default/*, allow'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
  namespace: openshift-gitops
spec:
  destinations:
    - name: '*'
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  roles:
    - name: cicd-admins
      policies:
        - 'p, proj:default:cicd-admins, applications, get, default/*, allow'
        - 'p, proj:default:cicd-admins, applications, sync, default/*, allow'
  sourceRepos:
    - 'https://github.com/piomin/openshift-cluster-config'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: cicd
  source:
    path: cicd
    repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
    targetRevision: HEAD
    directory:
      recurse: true