{{- $shortProviders := dict "Google" "GCP" "Azure" "Azure" "Amazon" "AWS" -}}
{{- $shortProvidersLowercase := dict "Google" "gcp" "Azure" "azure" "Amazon" "aws" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.clusterName }}
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
  labels:
    cloud: {{ get $shortProviders .Values.provider }}
    region: {{ .Values.region }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: {{ .Values.managedSet }}
spec:
  baseDomain: {{ .Values.baseDomain }}
  clusterName: {{ .Values.clusterName }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    {{ get $shortProvidersLowercase .Values.provider }}:
      credentialsSecretRef:
        name: {{ .Values.clusterName }}-{{ get $shortProvidersLowercase .Values.provider }}-creds
      region: europe-west1
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.clusterName }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.clusterName }}-ssh-private-key
    imageSetRef:
      name: img4.10.47-x86-64-appsub
      #img4.11.16-x86-64-appsub
  pullSecretRef:
    name: {{ .Values.clusterName }}-pull-secret