{{- $shortProvidersLowercase := dict "Google" "gcp" "Azure" "azure" "Amazon" "aws" -}}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.clusterName }}-worker
  namespace: {{ .Values.clusterName }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.clusterName }}
  name: worker
  platform:
    {{ get $shortProvidersLowercase .Values.provider }}:
      type: {{ .Values.workerType }}
  replicas: {{ .Values.workerReplicas }}