kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-cicd
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: app-owners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: app-owners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-stage
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: app-owners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pminkows-access
  namespace: pminkows-test
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: app-owners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin